modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="mo_fruits"
version="0.0.1"
displayName="Mo' Fruits"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Makc, MCreator"
description='''
more way to explore, fight, farm!
'''

[[dependencies.mo_fruits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



